In [1]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
ch=fetch_california_housing()
print(ch)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characte

In [2]:
x=pd.DataFrame(ch.data,columns=ch.feature_names)
y=pd.DataFrame(ch.target, columns=["AveInc"])
data=pd.concat([x,y],axis=1)
data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  AveInc  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [3]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x=pd.DataFrame(iris.data, columns=iris.feature_names)
y=pd.DataFrame(iris['target_names'][iris['target']], columns=['species'])
iris_df=pd.concat([x,y], axis=1)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [5]:
import statsmodels.api as sm
iris_data = sm.datasets.get_rdataset('iris',package='datasets')
iris_data.title

"Edgar Anderson's Iris Data"

In [6]:
print(iris_data.__doc__)

+------+-----------------+
| iris | R Documentation |
+------+-----------------+

Edgar Anderson's Iris Data
--------------------------

Description
~~~~~~~~~~~

This famous (Fisher's or Anderson's) iris data set gives the
measurements in centimeters of the variables sepal length and width and
petal length and width, respectively, for 50 flowers from each of 3
species of iris. The species are *Iris setosa*, *versicolor*, and
*virginica*.

Usage
~~~~~

::

   iris
   iris3

Format
~~~~~~

``iris`` is a data frame with 150 cases (rows) and 5 variables (columns)
named ``Sepal.Length``, ``Sepal.Width``, ``Petal.Length``,
``Petal.Width``, and ``Species``.

``iris3`` gives the same data arranged as a 3-dimensional array of size
50 by 4 by 3, as represented by S-PLUS. The first dimension gives the
case number within the species subsample, the second the measurements
with names ``Sepal L.``, ``Sepal W.``, ``Petal L.``, and ``Petal W.``,
and the third the species.

Source
~~~~~~

Fisher, R. A. 

In [7]:
print(iris_data.data)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [8]:
import statsmodels.api as sm
titanic_data=sm.datasets.get_rdataset('Titanic',package='datasets')
titanic_data

<class 'statsmodels.datasets.utils.Dataset'>

In [9]:
titanic_data.data.head()

Class     Sex    Age Survived  Freq
0   1st    Male  Child       No     0
1   2nd    Male  Child       No     0
2   3rd    Male  Child       No    35
3  Crew    Male  Child       No     0
4   1st  Female  Child       No     0

In [10]:
import statsmodels.api as sm
airpassengers_data=sm.datasets.get_rdataset('AirPassengers')
airpassengers=airpassengers_data.data
airpassengers.head()

time  value
0  1949.000000    112
1  1949.083333    118
2  1949.166667    132
3  1949.250000    129
4  1949.333333    121

In [11]:
def yearfraction2datetime(yearfraction, startyear=0):
    import  datetime
    import dateutil
    year=int(yearfraction)+startyear
    month=int(round(12*(yearfraction-year)))
    delta=dateutil.relativedelta.relativedelta(months=month)
    date=datetime.datetime(year,1,1)+delta
    return date

In [12]:
airpassengers['datetime']=airpassengers.time.map(yearfraction2datetime)
airpassengers.head()

time  value   datetime
0  1949.000000    112 1949-01-01
1  1949.083333    118 1949-02-01
2  1949.166667    132 1949-03-01
3  1949.250000    129 1949-04-01
4  1949.333333    121 1949-05-01

In [13]:
import seaborn as sns
iris=sns.load_dataset('iris')
x=iris.iloc[:,:-1]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [14]:
from sklearn.preprocessing import scale
x_scaled=scale(x)
x_scaled[:5,:]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [15]:
x_scaled.mean(axis=0)

for scaled_mean in x_scaled.mean(axis=0):
    print('{:10.9f}'.format(scaled_mean))
    

-0.000000000
-0.000000000
-0.000000000
-0.000000000


In [16]:
x_scaled.mean(axis=0)

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [17]:
for scaled_mean in x_scaled.mean(axis=0):
    print('{:10.9f}'.format(scaled_mean))

-0.000000000
-0.000000000
-0.000000000
-0.000000000


In [18]:
from sklearn.preprocessing import robust_scale
iris_robust_scaled=robust_scale(x)
iris_robust_scaled[:5,:]

array([[-0.53846154,  1.        , -0.84285714, -0.73333333],
       [-0.69230769,  0.        , -0.84285714, -0.73333333],
       [-0.84615385,  0.4       , -0.87142857, -0.73333333],
       [-0.92307692,  0.2       , -0.81428571, -0.73333333],
       [-0.61538462,  1.2       , -0.84285714, -0.73333333]])

In [19]:
from sklearn.preprocessing import minmax_scale
iris_minmax_scaled=minmax_scale(x)
iris_minmax_scaled[:5,:]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [20]:
from sklearn.preprocessing import maxabs_scale
iris_maxabs_scaled=maxabs_scale(x)
iris_maxabs_scaled[:5,:]

array([[0.64556962, 0.79545455, 0.20289855, 0.08      ],
       [0.62025316, 0.68181818, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.58227848, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.81818182, 0.20289855, 0.08      ]])

In [21]:
import seaborn as sns
iris=sns.load_dataset('iris')
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
iris_scaled=sc.fit_transform(iris.iloc[:,:-1])
iris_scaled[:5,:]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [22]:
iris_origin=sc.inverse_transform(iris_scaled)
iris_origin[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [24]:
# 추가 실습 내용
from sklearn.preprocessing import MinMaxScaler
min_max_scaler=MinMaxScaler()
iris_scaled=min_max_scaler.fit_transform(iris.iloc[:,:-1])
iris_scaled[:5,:]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [25]:
# 추가 실습 내용
iris_origin=min_max_scaler.inverse_transform(iris_scaled)
iris_origin[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [33]:
# 추가 실습 내용
from sklearn.preprocessing import MaxAbsScaler
max_abs_scaler=MaxAbsScaler()
# iris_scaled=max_abs_scaler.fit_transform(iris.iloc[:,:-1])
scaled_fix=max_abs_scaler.fit(iris.iloc[:,:-1])
iris_scaled=scaled_fix.transform(iris.iloc[:,:-1])
iris_scaled[:5,:]

array([[0.64556962, 0.79545455, 0.20289855, 0.08      ],
       [0.62025316, 0.68181818, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.58227848, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.81818182, 0.20289855, 0.08      ]])

In [30]:
# 추가 실습 내용
iris_origin=max_abs_scaler.inverse_transform(iris_scaled)
iris_origin[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [34]:
from sklearn.preprocessing import normalize
x=[[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]]
x_normalized_l1=normalize(x, norm='l1')
x_normalized_l1

array([[ 0.25, -0.25,  0.5 ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.5 , -0.5 ]])

In [35]:
x_normalized_l2=normalize(x, norm='l2')
x_normalized_l2

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [36]:
import seaborn as sns
iris=sns.load_dataset('iris')
y=iris.species
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
species=le.transform(y)
species

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [42]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder()
iris_onehot=enc.fit_transform(species.reshape(-1,1))
iris_onehot

c:\machine_learning\python_source\pythontest\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [40]:
iris_onehot.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [44]:
import seaborn as sns
iris=sns.load_dataset('iris')
x=iris.iloc[:,:-1]
import random
for col in range(4):
    x.iloc[[random.sample(range(len(iris)), 10)],col]=float('nan')
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           NaN          3.0           1.4          0.2
2           4.7          3.2           1.3          NaN
3           NaN          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [46]:
x.mean(axis=0)

sepal_length    5.874286
sepal_width     3.062143
petal_length    3.821429
petal_width     1.214286
dtype: float64

In [47]:
from sklearn.preprocessing import Imputer
imp_mean=Imputer(missing_values='NaN',strategy='mean',axis=0)
imp_mean.fit_transform(x)[0:5,:]

c:\machine_learning\python_source\pythontest\venv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [5.87428571, 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 1.21428571],
       [5.87428571, 3.1       , 1.5       , 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ]])

In [48]:
x.median(axis=0)

sepal_length    5.80
sepal_width     3.00
petal_length    4.45
petal_width     1.30
dtype: float64

In [49]:
imp_median=Imputer(missing_values='NaN',strategy='median',axis=0)
imp_median.fit_transform(x)[0:5,:]

c:\machine_learning\python_source\pythontest\venv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[5.1, 3.5, 1.4, 0.2],
       [5.8, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 1.3],
       [5.8, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [50]:
x.mode(axis=0)

sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.0           1.4          0.2

In [54]:
imp_mostfreq=Imputer(missing_values='NaN',strategy='most_frequent',axis=0)
imp_mostfreq.fit_transform(x)[0:5,:]

c:\machine_learning\python_source\pythontest\venv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[5.1, 3.5, 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [55]:
import seaborn as sns
iris_df=sns.load_dataset('iris')
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris_df.iloc[:,0:4],iris_df.species,test_size=0.3)
x_train.shape

(105, 4)

In [56]:
x_test.shape

(45, 4)

In [57]:
import pandas as pd
redwine=pd.read_csv('winequality-red.csv', delimiter=';')
X=redwine.iloc[:,:-1]
y=redwine.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [58]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [59]:
X_train_scaled

array([[0.26785714, 0.30821918, 0.27631579, ..., 0.26086957, 0.12962963,
        0.21538462],
       [0.375     , 0.34246575, 0.23684211, ..., 0.26086957, 0.33950617,
        0.12307692],
       [0.16964286, 0.34931507, 0.        , ..., 0.29565217, 0.07407407,
        0.16923077],
       ...,
       [0.28571429, 0.15753425, 0.60526316, ..., 0.42608696, 0.32716049,
        0.67692308],
       [0.40178571, 0.21232877, 0.64473684, ..., 0.32173913, 0.19135802,
        0.16923077],
       [0.27678571, 0.19863014, 0.89473684, ..., 0.19130435, 0.60493827,
        0.13846154]])

In [60]:
X_test_scaled

array([[0.3       , 0.30693069, 0.21      , ..., 0.37068966, 0.30573248,
        0.19642857],
       [0.70909091, 0.27722772, 0.51      , ..., 0.25862069, 0.10828025,
        0.16071429],
       [0.18181818, 0.83168317, 0.        , ..., 0.65517241, 0.00636943,
        0.625     ],
       ...,
       [0.33636364, 0.52475248, 0.1       , ..., 0.47413793, 0.07643312,
        0.19642857],
       [0.26363636, 0.2970297 , 0.32      , ..., 0.43103448, 0.00636943,
        0.35714286],
       [0.47272727, 0.32673267, 0.38      , ..., 0.35344828, 0.0955414 ,
        0.25      ]])

In [62]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=10).fit(X_train_scaled,y_train)
feature_importance_rf=pd.DataFrame(data=np.c_[X.columns.values, rf.feature_importances_], columns=['feature','importance'])
feature_importance_rf.sort_values('importance',ascending=False,inplace=True)
feature_importance_rf

feature importance
10               alcohol   0.150863
9              sulphates   0.112564
6   total sulfur dioxide   0.103426
1       volatile acidity  0.0919946
7                density  0.0878595
0          fixed acidity  0.0838384
5    free sulfur dioxide   0.079349
4              chlorides  0.0771644
2            citric acid  0.0738921
8                     pH  0.0735064
3         residual sugar   0.065542

In [64]:
X_train_scaled

array([[0.26785714, 0.30821918, 0.27631579, ..., 0.26086957, 0.12962963,
        0.21538462],
       [0.375     , 0.34246575, 0.23684211, ..., 0.26086957, 0.33950617,
        0.12307692],
       [0.16964286, 0.34931507, 0.        , ..., 0.29565217, 0.07407407,
        0.16923077],
       ...,
       [0.28571429, 0.15753425, 0.60526316, ..., 0.42608696, 0.32716049,
        0.67692308],
       [0.40178571, 0.21232877, 0.64473684, ..., 0.32173913, 0.19135802,
        0.16923077],
       [0.27678571, 0.19863014, 0.89473684, ..., 0.19130435, 0.60493827,
        0.13846154]])

In [65]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [68]:
from sklearn.feature_selection import RFE
select=RFE(RandomForestClassifier(n_estimators=5,random_state=42),n_features_to_select=7)
select.fit(X_train_scaled, y_train)
feature_importance_rfe=pd.DataFrame(data=np.c_[X.columns.values, select.get_support()], columns=['feature','importance'])
feature_importance_rfe.sort_values('importance',ascending=False,inplace=True)
feature_importance_rfe

feature importance
1       volatile acidity       True
4              chlorides       True
6   total sulfur dioxide       True
7                density       True
8                     pH       True
9              sulphates       True
10               alcohol       True
0          fixed acidity      False
2            citric acid      False
3         residual sugar      False
5    free sulfur dioxide      False

In [69]:
# 실습을 위한 데이터
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [70]:
# 표준화
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [71]:
X_train_scaled

array([[0.04235883, 0.        , 0.64662757, ..., 0.80851064, 0.05469262,
        0.42549669],
       [0.00139665, 0.        , 0.35007331, ..., 0.55319149, 0.85306874,
        0.37637969],
       [0.00836171, 0.        , 0.28152493, ..., 0.89361702, 0.99351959,
        0.40204194],
       ...,
       [0.01399878, 0.        , 0.28152493, ..., 0.89361702, 0.9487367 ,
        0.53228477],
       [0.01103868, 0.        , 0.28152493, ..., 0.89361702, 0.99404912,
        0.50082781],
       [0.00224525, 0.22      , 0.19794721, ..., 0.69148936, 0.93844874,
        0.29718543]])

In [72]:
X_test_scaled

array([[1.35997132e-01, 0.00000000e+00, 6.36637769e-01, ...,
        8.00000000e-01, 9.93737005e-01, 4.52063492e-01],
       [1.00000000e+00, 0.00000000e+00, 6.36637769e-01, ...,
        8.00000000e-01, 2.02850043e-04, 2.29841270e-01],
       [1.03869326e-02, 2.10526316e-01, 1.04033170e-01, ...,
        0.00000000e+00, 9.89603935e-01, 2.13333333e-01],
       ...,
       [9.27107811e-04, 0.00000000e+00, 4.37994723e-01, ...,
        6.33333333e-01, 9.73375932e-01, 3.00634921e-01],
       [5.22622800e-04, 2.10526316e-01, 7.99095364e-02, ...,
        2.11111111e-01, 9.75683351e-01, 2.82539683e-02],
       [6.64036080e-04, 8.42105263e-01, 2.63852243e-02, ...,
        1.00000000e+00, 9.64247680e-01, 1.64444444e-01]])

In [74]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
model_boston=LinearRegression().fit(X_train_scaled,y_train)
cross_val_score(model_boston, X_train_scaled,y_train,cv=5)

array([0.8297386 , 0.55317023, 0.69258143, 0.65559514, 0.6583547 ])

In [76]:
model_boston.coef_

array([-10.09427281,   4.98143505,   1.83301569,   3.25758511,
        -7.48628708,  16.93306629,   0.91721546, -13.773304  ,
         7.63866169,  -5.65630411,  -7.72637779,   4.76162338,
       -23.7436683 ])

In [77]:
import pandas as pd
import numpy as np
feature_importance_lr=pd.DataFrame(np.c_[boston.feature_names, model_boston.coef_.ravel()])
feature_importance_lr.columns=['feature','coef']
feature_importance_lr.sort_values('coef', ascending=False,inplace=True)
feature_importance_lr

feature                 coef
8       RAD    7.638661689406938
1        ZN   4.9814350508585825
11        B    4.761623377976285
3      CHAS   3.2575851093985415
5        RM    16.93306628904684
2     INDUS    1.833015689286528
6       AGE   0.9172154640064711
10  PTRATIO   -7.726377794843847
4       NOX   -7.486287083471288
9       TAX   -5.656304110060977
12    LSTAT  -23.743668300772697
7       DIS  -13.773304002144629
0      CRIM  -10.094272810423233

In [78]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2
X, y=load_iris(return_X_y=True)
X.shape

(150, 4)

In [85]:
X_new=SelectKBest(chi2,k=3).fit_transform(X,y)
X_new.shape

(150, 3)

In [80]:
X_new

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [1.5],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.4],
       [1.3],
       [1.5],
       [1.3],
       [1.3],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [87]:
import pandas as pd
import numpy as np

redwine=pd.read_csv('winequality-red.csv', delimiter=';')
redwine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [88]:
# 데이터셋 샘플링
train=redwine.sample(frac=0.7) # 학습 데이터 생성
test=redwine.loc[~redwine.index.isin(train.index)] # 테스트 데이터 생성
train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
76              8.8             0.410         0.64             2.2      0.093   
1226            7.5             0.580         0.03             4.1      0.080   
1526            6.8             0.470         0.08             2.2      0.064   
1456            6.0             0.540         0.06             1.8      0.050   
109             8.1             0.785         0.52             2.0      0.122   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
76                    9.0                  42.0  0.99860  3.54       0.66   
1226                 27.0                  46.0  0.99592  3.02       0.47   
1526                 18.0                  38.0  0.99553  3.30       0.65   
1456                 38.0                  89.0  0.99236  3.30       0.50   
109                  37.0                 153.0  0.99690  3.21       0.69   

      alcohol  quality  
76      10.50        5  
1226     9.20        5  
1526     9.60        6  
1456    10.55        6  
109      9.30        5

In [92]:
print(train.shape, test.shape)

(1119, 12) (480, 12)


In [107]:
train_x=train.iloc[:,:-1]
train_y=train.iloc[:,:-1]
test_x=test.iloc[:,:-1]
test_y=test.iloc[:,:-1]

In [111]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(50,30))

In [118]:
mlp.fit(train_x, train_y)

ValueError: Multioutput target data is not supported with label binarization

In [117]:
pred=mlp.predict(test_x)
pred

NotFittedError: This MLPClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.